# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='owner',
            new_name='user',
        ),
    ]
