# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20170907_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student_number',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
