# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20170908_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuous_assessment',
            name='marks_ptr',
        ),
        migrations.DeleteModel(
            name='Continuous_Assessment',
        ),
    ]
