# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20170908_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='marks',
            name='surname',
            field=models.CharField(max_length=40),
        ),
    ]
