# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20180205_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eschool.Student'),
        ),
    ]
