# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20180205_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='subject_ID',
            new_name='subject_name',
        ),
    ]
