# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('published_date', models.DateField()),
                ('Author', models.CharField(max_length=50)),
                ('book_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('book_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=50)),
                ('date_taken', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('invoice_number', models.CharField(max_length=50)),
                ('tutoring_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Bank_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('Phonenumber', models.CharField(max_length=10)),
                ('Physical_Address', models.CharField(max_length=200)),
                ('Email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Image', models.FileField(upload_to='uploads/')),
                ('DOB', models.DateField()),
                ('NID', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(max_length=50)),
                ('landline_number', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('Phonenumber', models.CharField(max_length=10)),
                ('Physical_Address', models.CharField(max_length=200)),
                ('Email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Image', models.FileField(upload_to='uploads/')),
                ('DOB', models.DateField()),
                ('student_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_name', models.CharField(max_length=20)),
                ('subject_ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('Phonenumber', models.CharField(max_length=10)),
                ('Physical_Address', models.CharField(max_length=200)),
                ('Email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Image', models.FileField(upload_to='uploads/')),
                ('DOB', models.DateField()),
                ('EmploymentID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('subject_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eschool.Subjects')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='parents',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eschool.Students'),
        ),
        migrations.AddField(
            model_name='fees',
            name='Student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eschool.Students'),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eschool.Students'),
        ),
    ]
